Aro migration devhub content
bcgov/devhub-app-web pull request #1486
Opened 2020-09-29 18:02 UTC by patricksimonian

## Summary
Added aro migration docs :)

2020-09-29 18:02 UTC, patricksimonian commented
@deploy-tron help

2020-09-29 18:06 UTC, patricksimonian commented
@deploy-tron deploy web to dev

2020-09-29 18:09 UTC, ShellyXueHan requested changes

2020-09-29 18:09 UTC, ShellyXueHan commented on app-web/topicRegistry/cloud-migration.md
> +            "resources/aro/migrating-rhel-images.md
missing quote

2020-09-29 18:11 UTC, patricksimonian commented on app-web/topicRegistry/cloud-migration.md
> +            "resources/aro/migrating-rhel-images.md
oh shoot! good eye 🤠

2020-09-29 18:12 UTC, patricksimonian commented on app-web/topicRegistry/cloud-migration.md
> +            "resources/aro/migrating-rhel-images.md
```suggestion
            "resources/aro/migrating-rhel-images.md"
```

2020-09-29 18:13 UTC, patricksimonian commented
@deploy-tron deploy web to dev

2020-09-29 18:44 UTC, patricksimonian commented
@deploy-tron deploy web to prod

2020-09-29 18:50 UTC, patricksimonian commented
@deploy-tron deploy web to prod

2020-09-29 20:45 UTC, patricksimonian commented
@deploy-tron deploy web to test

2020-09-29 21:25 UTC, patricksimonian commented
@deploy-tron deploy web to dev

2020-09-30 17:14 UTC, patricksimonian commented
@deploy-tron deploy web to test

2020-09-30 17:39 UTC, patricksimonian commented
@deploy-tron deploy web to prod

2020-09-30 21:56 UTC, patricksimonian commented
@deploy-tron deploy web to dev

2020-09-30 22:39 UTC, patricksimonian commented
@deploy-tron deploy web to test

2020-09-30 22:40 UTC, patricksimonian commented
@deploy-tron deploy web to prod

2020-09-30 22:50 UTC, patricksimonian commented
@deploy-tron deploy web to test

2020-09-30 23:12 UTC, patricksimonian commented
@deploy-tron deploy web to prod

2020-09-30 23:29 UTC, patricksimonian commented
@deploy-tron deploy web to staging

2020-09-30 23:35 UTC, patricksimonian commented
@deploy-tron deploy web to prod

2020-10-01 20:53 UTC, ShellyXueHan approved these changes

2020-10-01 21:20 UTC, merged