Create ag-pssg.json
bcgov/devhub-app-web pull request #1527
Opened 2020-12-21 18:53 UTC by AubreyR

## Summary
Example PR for content contribution

## Notable Changes 
added a carousel under topics
-
-

2020-12-21 19:34 UTC, patricksimonian requested changes

2020-12-21 19:34 UTC, patricksimonian commented on app-web/topicRegistry/ag-pssg.json
> +            "README.md",
no trailing commas in json :)

2020-12-21 19:34 UTC, patricksimonian commented on app-web/topicRegistry/ag-pssg.json
> +            "README.md",
```suggestion
            "README.md"
```

2020-12-22 21:22 UTC, patricksimonian commented on app-web/topicRegistry/ag-pssg.json
> +          "owner": "AubreyR",
```suggestion
          "owner": "AubreyR",
          "branch": "main",
```

2020-12-22 21:22 UTC, patricksimonian requested changes
last change

2020-12-24 21:39 UTC, AubreyR commented
Everything worked for my demo!  Closing this now!

2020-12-24 21:39 UTC, closed without merging